services:
  DemoActionsAPI:
    image: demonactionsapi
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  nginx_conf:
  html:
  certs: