FROM nginx:alpine

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates
COPY ./dev-certs/selfsigned.crt /etc/nginx/certificate.crt
COPY ./dev-certs/selfsigned.key /etc/nginx/private.key

# Expose ports
EXPOSE 80
EXPOSE 443