version: '3.8'

services:
  DemoActionsAPI:
    image: demonactionsapi
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
