version: '3.8'

services:
  DemoActionsAPI:
    image: demonactionsapi
    container_name: DemoActionsAPI
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"